export type AutomationDocumentTrigger =
  | "employee.hired"
  | "employee.moved"
  | "employee.promoted"
  | "employee.separated";

export type AutomationDocumentSnapshot = {
  generatedAt: string;
  organizationName?: string | null;
  legalEntityName?: string | null;
  legalEntityCode?: string | null;
  employeeId: number;
  employeeNo: string;
  employeeName: string;
  employeeEmail?: string | null;
  employeeTitle?: string | null;
  employmentType?: string | null;
  employeeStatus?: string | null;
  employeeStartDate?: string | null;
  department?: string | null;
  trigger: AutomationDocumentTrigger;
  effectiveDate?: string | null;
  movementType?: string | null;
  previousOrgUnitId?: number | null;
  previousPositionId?: number | null;
  positionId?: number | null;
  positionCode?: string | null;
  managerName?: string | null;
};

export type AutomationDocumentTemplate = {
  id: string;
  version: number;
  name: string;
  description: string;
  kind: string;
  allowedTriggers: readonly AutomationDocumentTrigger[];
  render: (snapshot: AutomationDocumentSnapshot) => string;
};

function safe(value: unknown) {
  return String(value ?? "").replace(/[\r\n\t]+/g, " ").trim() || "Not recorded";
}

function header(title: string, snapshot: AutomationDocumentSnapshot) {
  return [
    title,
    "=".repeat(title.length),
    "",
    "Generated by PayrollPH from authoritative worker data.",
    "This system-generated record does not replace a signed employment contract, statutory notice, legal advice, or employee acknowledgement.",
    "",
    `Generated at: ${safe(snapshot.generatedAt)}`,
    `Legal employer: ${safe(snapshot.legalEntityName)}${snapshot.legalEntityCode ? ` (${safe(snapshot.legalEntityCode)})` : ""}`,
    `Employee: ${safe(snapshot.employeeName)}`,
    `Employee no.: ${safe(snapshot.employeeNo)}`,
    "",
  ];
}

function workerLines(snapshot: AutomationDocumentSnapshot) {
  return [
    `Job title: ${safe(snapshot.employeeTitle)}`,
    `Employment type: ${safe(snapshot.employmentType)}`,
    `Worker status: ${safe(snapshot.employeeStatus)}`,
    `Department / org unit: ${safe(snapshot.department)}`,
    `Start date: ${safe(snapshot.employeeStartDate)}`,
    `Manager: ${safe(snapshot.managerName)}`,
  ];
}

const templates: AutomationDocumentTemplate[] = [
  {
    id: "employee-onboarding-summary",
    version: 1,
    name: "Employee onboarding summary",
    description: "Creates an employee-facing operational summary of the worker record after an authoritative hire event.",
    kind: "generated_onboarding_summary",
    allowedTriggers: ["employee.hired"],
    render(snapshot) {
      return [
        ...header("Employee Onboarding Summary", snapshot),
        ...workerLines(snapshot),
        "",
        "Purpose",
        "-------",
        "Use this summary to review the worker information currently recorded in PayrollPH. Report incorrect employment, payroll, manager, or organization details to People Ops through the governed correction process.",
        "",
      ].join("\n");
    },
  },
  {
    id: "employee-movement-notice",
    version: 1,
    name: "Employee movement notice",
    description: "Creates an operational record after an authoritative worker move or promotion has applied.",
    kind: "generated_movement_notice",
    allowedTriggers: ["employee.moved", "employee.promoted"],
    render(snapshot) {
      return [
        ...header("Employee Movement Notice", snapshot),
        `Effective date: ${safe(snapshot.effectiveDate)}`,
        `Movement type: ${safe(snapshot.movementType ?? snapshot.trigger.replace("employee.", ""))}`,
        `Current position code: ${safe(snapshot.positionCode)}`,
        `Previous position ID: ${safe(snapshot.previousPositionId)}`,
        `Current position ID: ${safe(snapshot.positionId)}`,
        `Previous org unit ID: ${safe(snapshot.previousOrgUnitId)}`,
        `Current department / org unit: ${safe(snapshot.department)}`,
        `Current title: ${safe(snapshot.employeeTitle)}`,
        `Current manager: ${safe(snapshot.managerName)}`,
        "",
        "Purpose",
        "-------",
        "This notice records the applied worker movement for operational review. It does not replace a compensation notice, signed amendment, or legally required employment communication.",
        "",
      ].join("\n");
    },
  },
  {
    id: "employee-separation-handoff-summary",
    version: 1,
    name: "Employee separation handoff summary",
    description: "Creates an operational offboarding handoff record after an authoritative employee separation event.",
    kind: "generated_separation_summary",
    allowedTriggers: ["employee.separated"],
    render(snapshot) {
      return [
        ...header("Employee Separation Handoff Summary", snapshot),
        `Separation/effective date: ${safe(snapshot.effectiveDate)}`,
        `Recorded worker status: ${safe(snapshot.employeeStatus)}`,
        `Department / org unit: ${safe(snapshot.department)}`,
        `Manager: ${safe(snapshot.managerName)}`,
        "",
        "Operational handoff",
        "-------------------",
        "Use the governed PayrollPH offboarding, payroll, access, asset, and compliance workflows as the authoritative completion evidence. This generated summary does not itself prove final pay, clearance, access revocation, asset return, or statutory compliance.",
        "",
      ].join("\n");
    },
  },
];

export const AUTOMATION_DOCUMENT_TEMPLATES = templates;

export function getAutomationDocumentTemplate(templateId: string) {
  return AUTOMATION_DOCUMENT_TEMPLATES.find((template) => template.id === templateId) ?? null;
}
