/** Employee-facing display copy only; never translate stored statutory codes or payroll line items. */
export type EssLanguage = "en" | "fil";
export const ESS_LANGUAGE_STORAGE_KEY = "linaw.ess.display-language";

const taglishCopy: Readonly<Record<string, string>> = {
  "Language": "Wika",
  "Display language": "Wika ng display",
  "English": "English",
  "Taglish": "Taglish",
  "Home": "Home",
  "Pay": "Sahod",
  "Payslips": "Mga payslip",
  "Time": "Oras",
  "Attendance": "Attendance",
  "Leave": "Leave",
  "Documents": "Mga dokumento",
  "Performance": "Performance",
  "Profile": "Profile",
  "My info": "Impormasyon ko",
  "Employee navigation": "Navigation ng empleyado",
  "Employee pages": "Mga pahina ng empleyado",
  "Employee workspace": "Employee workspace",
  "Your employer": "Employer mo",
  "Time clock": "Time clock",
  "More": "Iba pa",
  "More from Linaw": "Iba pang pahina sa Linaw",
  "Sign out": "Mag-sign out",
  "Signing out…": "Nag-sign out…",
  "Open profile": "Buksan ang profile",
  "Open time clock": "Buksan ang time clock",
  "Close more pages": "Isara ang iba pang pahina",
  "EMPLOYEE SELF-SERVICE": "EMPLOYEE SELF-SERVICE",
  "Link your employee record": "I-link ang employee record mo",
  "This one-time step connects your login to exactly one employee record. After that, you can see only your own pay, time and leave.": "Isang beses lang ito para i-link ang account mo sa isang employee record. Pagkatapos, sariling sahod, attendance, at leave mo lang ang makikita mo.",
  "Employee number": "Employee number",
  "Linked. Loading your account…": "Naka-link na. Nilo-load ang account mo…",
  "Linking…": "Nili-link…",
  "Link my record": "I-link ang record ko",
  "Good morning": "Kumusta",
  "Your pay, leave and attendance at a glance.": "Sahod, leave, at attendance mo sa isang tingin.",
  "My leave": "Leave ko",
  "Next payday": "Susunod na payday",
  "Not scheduled yet": "Wala pang schedule",
  "Your next cycle appears when you’re included in a payroll run.": "Lalabas ang susunod na pay period kapag kasama ka na sa payroll run.",
  "Your payslip will be available after payroll is released.": "Available ang payslip mo pagkatapos ma-release ang payroll.",
  "Leave balance": "Natitirang leave",
  "days": "araw",
  "No leave policy assigned yet.": "Wala pang naka-assign na leave policy.",
  "requests awaiting approval": "leave request na naghihintay ng approval",
  "No pending leave requests": "Walang pending na leave request",
  "View leave details": "Tingnan ang leave details",
  "complete": "kumpleto",
  "Of": "Sa",
  "recent time records": "recent time records",
  "Today’s shift is complete": "Kumpleto na ang shift mo ngayong araw",
  "You’re clocked in": "Naka-time in ka",
  "Not clocked in today": "Hindi ka pa naka-time in ngayong araw",
  "Latest payslip": "Pinakabagong payslip",
  "No released payslip yet": "Wala pang na-release na payslip",
  "Payslip available · Net pay · Paid": "Available ang payslip · Net pay · Binayaran noong",
  "Your released pay will appear here.": "Dito lalabas ang sahod mo pagkatapos ma-release.",
  "View payslip": "Tingnan ang payslip",
  "Request leave": "Mag-request ng leave",
  "View attendance": "Tingnan ang attendance",
  "Recent payslips": "Mga nakaraang payslip",
  "View all": "Tingnan lahat",
  "Paid": "Binayaran noong",
  "No released payslips yet.": "Wala pang na-release na payslip.",
  "NEXT PAY STATUS": "STATUS NG SUSUNOD NA PAY",
  "Your pay amount stays private and hidden until payroll is released.": "Pribado ang halaga ng sahod mo at hindi ito ipinapakita hangga't hindi pa released ang payroll.",
  "MY PAY": "SAHOD KO",
  "Latest released pay first. Draft and in-review payroll amounts never appear here.": "Unang makikita ang pinakahuling released pay. Hindi ipinapakita rito ang draft o nirereview pang payroll.",
  "Net pay": "Net pay (take-home)",
  "Net pay · paid": "Net pay · binayaran noong",
  "Gross": "Gross pay (bago ang kaltas)",
  "Deductions": "Deductions (mga kaltas)",
  "Tax withheld YTD": "Tax na nakaltas ngayong taon",
  "Earnings": "Earnings (mga kinita)",
  "No positive pay lines stored.": "Walang naitalang positibong earnings line.",
  "No deductions stored.": "Walang naitalang deductions.",
  "Rule version": "Bersyon ng payroll rule",
  "PAY HISTORY": "PAY HISTORY",
  "released period": "released pay period",
  "released periods": "released pay periods",
  "Download PDF": "I-download ang PDF",
  "Why did my pay change?": "Bakit nagbago ang sahod ko?",
  "Comparing this payslip with your previous released pay...": "Kinukumpara ang payslip na ito sa naunang released pay...",
  "We could not explain this payslip.": "Hindi maipaliwanag ang payslip na ito ngayon.",
  "We could not load the explanation because the server could not be reached.": "Hindi ma-load ang paliwanag dahil hindi maabot ang server.",
  "EXPLAIN MY PAY": "PALIWANAG SA SAHOD",
  "This uses the stored payroll calculation and compares it with your previous released cutoff. It does not recalculate your pay in the browser.": "Galing ito sa naka-save na payroll calculation at ikinukumpara sa naunang released cutoff. Hindi nire-recompute ang sahod sa browser.",
  "Your previous released pay is available, but no net-pay comparison was produced.": "May naunang released pay, pero walang available na paghahambing ng net pay.",
  "Your net pay is unchanged from": "Hindi nagbago ang net pay mo kumpara sa",
  "Your net pay is": "Ang net pay mo ay",
  "higher": "mas mataas",
  "lower": "mas mababa",
  "than": "kumpara sa",
  "This is the first released payroll in your available history, so there is no earlier cutoff to compare yet.": "Ito ang unang released payroll sa available mong history, kaya wala pang naunang cutoff na maikukumpara.",
  "Current net": "Kasalukuyang net pay",
  "Previous net": "Nakaraang net pay",
  "Net change": "Pagbabago sa net pay",
  "No prior pay": "Walang naunang pay",
  "Not available": "Hindi available",
  "No net change": "Walang pagbabago sa net pay",
  "Current:": "Kasalukuyan:",
  "Current pay": "Kasalukuyang sahod",
  "effect on net": "epekto sa net pay",
  "Show main changes": "Ipakita ang pangunahing pagbabago",
  "Show all": "Ipakita lahat ng",
  "pay components": "pay components",
  "Explanation from stored payroll data · rule version": "Paliwanag mula sa naka-save na payroll data · bersyon ng rule",
  "MY LEAVE": "LEAVE KO",
  "Check your available days and request leave without seeing anyone else’s records.": "Tingnan ang available leave days at mag-request ng leave nang hindi nakikita ang record ng iba.",
  "No active leave policy is configured for your employer.": "Wala pang active leave policy na naka-configure ang employer mo.",
  "days available ·": "araw na available ·",
  "pending": "pending",
  "REQUESTS": "MGA REQUEST",
  "Recent leave requests": "Mga nakaraang leave request",
  "No leave requests yet.": "Wala pang leave request.",
  "MY PROFILE": "PROFILE KO",
  "Personal details": "Personal na detalye",
  "You can update contact details. Payroll-sensitive employment, bank and government records stay controlled by HR.": "Puwede mong i-update ang contact details mo. Ang sensitibong employment, bank, at government payroll records ay HR pa rin ang namamahala.",
  "Cancel": "Kanselahin",
  "Edit contact details": "I-edit ang contact details",
  "Role": "Role",
  "Start date": "Petsa ng pagsisimula",
  "Rest day": "Rest day",
  "Not configured": "Hindi pa naka-configure",
  "Work email": "Work email",
  "Not recorded": "Walang record",
  "Contact HR to change this payroll record.": "Kontakin ang HR para baguhin ang payroll record na ito.",
  "Mobile": "Mobile",
  "Emergency contact": "Emergency contact",
  "Emergency phone": "Emergency phone",
  "Save contact details": "I-save ang contact details",
  "Saving…": "Sine-save…",
  "Your pay, time, leave and profile queries are bound to your employee ID from the signed-in session. Editing a URL does not switch whose records are returned.": "Nakaugnay sa employee ID ng naka-login na account ang pay, time, leave, at profile mo. Hindi mababago ng pag-edit ng URL ang records na makikita mo.",
  "REQUEST LEAVE": "MAG-REQUEST NG LEAVE",
  "New leave request": "Bagong leave request",
  "Your request will be sent to a separate approver configured by your employer.": "Ipapadala ang request mo sa hiwalay na approver na itinakda ng employer.",
  "Leave type": "Uri ng leave",
  "End date": "Petsa ng pagtatapos",
  "Leave days": "Bilang ng leave days",
  "Enter the actual leave days. The app does not guess weekends, rest days or holidays.": "Ilagay ang aktuwal na leave days. Hindi awtomatikong hinuhulaan ang weekends, rest days, o holidays.",
  "Reason": "Dahilan",
  "Submitting…": "Isinusumite…",
  "Submit request": "Isumite ang request"
};

/** Unknown text (especially source/payroll evidence) stays byte-for-byte as supplied. */
export function essText(language: EssLanguage, english: string): string {
  if (language !== "fil") return english;
  return Object.prototype.hasOwnProperty.call(taglishCopy, english)
    ? taglishCopy[english]
    : english;
}

export function parseEssLanguage(input: unknown): EssLanguage {
  return input === "fil" ? "fil" : "en";
}
