import type { AuthorityPage } from "@/lib/seo-content";

export const resourceWave2: AuthorityPage[] = [
  {
    slug: "cloud-vs-on-premise-payroll",
    eyebrow: "Payroll deployment comparison",
    title: "Cloud payroll vs on-premise payroll in the Philippines.",
    description: "Compare cloud and on-premise payroll across updates, security, access, infrastructure, continuity and implementation effort.",
    intro: "Deployment model affects far more than where payroll software runs. It changes who owns infrastructure, updates, remote access, disaster recovery and rollout complexity.",
    proof: ["Infrastructure ownership", "Update cadence", "Remote access", "Security responsibilities", "Backup and recovery", "Implementation effort"],
    sections: [
      { title: "Cloud reduces local infrastructure ownership", body: "A cloud payroll system shifts application hosting and deployment operations away from local servers, but buyers should still ask how access, backups and production controls are implemented." },
      { title: "On-premise can provide infrastructure control", body: "On-premise deployments may suit organizations with specific internal hosting requirements, but they also place more responsibility on the buyer for uptime, patching and recovery." },
      { title: "Compare operational ownership, not just licensing", body: "The important question is who is accountable for upgrades, security maintenance, availability, incident response and business continuity." },
      { title: "Migration quality matters more than the deployment label", body: "A move to cloud payroll should still include data mapping, validation, reconciliation, role setup and a controlled go-live." },
    ],
    related: [
      { label: "Implementation", href: "/implementation", description: "See the migration and reconciliation model." },
      { label: "Security checklist", href: "/resources/payroll-security-checklist", description: "Evaluate security responsibilities before choosing a deployment model." },
      { label: "Payroll software buyer guide", href: "/resources/best-payroll-software-philippines", description: "Compare deployment alongside calculation and workflow depth." },
    ],
  },
  {
    slug: "payroll-rfp-checklist",
    eyebrow: "Payroll RFP checklist",
    title: "Payroll software RFP checklist for Philippine buyers.",
    description: "A procurement checklist for evaluating payroll vendors across calculations, compliance, controls, implementation, security, integrations and support.",
    intro: "A good payroll RFP forces vendors to demonstrate the difficult parts of payroll rather than answering a generic yes-or-no feature matrix.",
    proof: ["Calculation scenarios", "Approval controls", "Migration plan", "Security evidence", "API and exports", "Support ownership"],
    sections: [
      { title: "Require scenario-based payroll demonstrations", body: "Ask vendors to price the exact overtime, holiday, rest-day, night-shift, deduction and employee cases that create complexity in your payroll." },
      { title: "Request evidence for controls", body: "Ask how users are authenticated, how access is scoped, who can approve payroll and how actions are reconstructed later." },
      { title: "Make implementation part of the RFP", body: "Require a data migration plan, reconciliation process, parallel or controlled payroll, training approach and go-live criteria." },
      { title: "Separate built capability from roadmap promises", body: "Ask which items are live today, which depend on third parties and which are planned but unavailable." },
    ],
    related: [
      { label: "Capability scorecard", href: "/scorecard", description: "See a verified/partial/absent product evidence model." },
      { label: "Payroll security checklist", href: "/resources/payroll-security-checklist", description: "Use deeper security questions in procurement." },
      { label: "Live demo", href: "/demo", description: "Test the product by role instead of relying on slides." },
    ],
  },
  {
    slug: "payroll-implementation-guide",
    eyebrow: "Payroll implementation guide",
    title: "How to implement a new payroll system without losing control.",
    description: "A practical Philippine payroll implementation guide covering discovery, migration, roles, reconciliation, rollout and post-launch checks.",
    intro: "Payroll implementation should reduce uncertainty in stages. The goal is not simply to load data and switch systems, but to prove the new process before the first production release.",
    proof: ["Discovery", "Data mapping", "Role setup", "Reconciliation", "Controlled rollout", "Post-launch review"],
    sections: [
      { title: "Document the current payroll before changing it", body: "Capture pay frequencies, employee groups, attendance sources, recurring deductions, benefits, approvals, reports, exports and known manual exceptions." },
      { title: "Migrate the minimum data needed for a provable run", body: "Prioritize employee records, payroll configuration, current balances and year-to-date values that directly affect the next payroll." },
      { title: "Run an independent reconciliation", body: "Compare expected gross pay, statutory deductions, tax, net pay, payout totals and employee-level results outside the new system before release." },
      { title: "Treat go-live as a controlled decision", body: "Define who signs off, what unresolved exceptions block release and what monitoring happens after the first production payroll." },
    ],
    related: [
      { label: "Implementation", href: "/implementation", description: "See Linaw's implementation workflow." },
      { label: "Migration checklist", href: "/resources/payroll-migration-checklist", description: "Use a detailed data and reconciliation checklist." },
      { label: "Payroll health check", href: "/payroll-health-check", description: "Assess current process weaknesses before implementation." },
    ],
  },
  {
    slug: "payroll-software-roi",
    eyebrow: "Payroll software ROI",
    title: "How to evaluate the ROI of payroll software.",
    description: "A practical framework for estimating payroll software ROI from processing time, error rework, compliance effort, support workload and control improvements.",
    intro: "Payroll ROI should not be reduced to subscription cost. The useful comparison measures recurring manual effort, rework, operational risk and the cost of maintaining disconnected processes.",
    proof: ["Processing hours", "Rework", "Employee support", "Manual exports", "Control overhead", "Implementation cost"],
    sections: [
      { title: "Measure the current process first", body: "Track hours spent on attendance cleanup, payroll calculation, checking, employee questions, reports, exports and correction cycles." },
      { title: "Count recurring rework", body: "Corrections caused by duplicate encoding, formula changes, incomplete attendance and disconnected approvals are part of payroll cost even when they are not separately invoiced." },
      { title: "Include implementation and change costs", body: "Software ROI should include migration, training and process redesign instead of assuming implementation is free." },
      { title: "Value stronger controls separately from labor savings", body: "Approval separation, auditability and rule consistency may justify a system even when headcount savings are not the primary objective." },
    ],
    related: [
      { label: "Payroll software vs Excel", href: "/resources/payroll-software-vs-excel", description: "Compare controlled workflow with spreadsheet operations." },
      { label: "Pricing", href: "/pricing", description: "Review the current product pricing catalog." },
      { label: "Payroll health check", href: "/payroll-health-check", description: "Identify process risks that may be contributing to payroll cost." },
    ],
  },
  {
    slug: "build-vs-buy-payroll-software",
    eyebrow: "Build vs buy payroll software",
    title: "Build vs buy payroll software for Philippine businesses.",
    description: "Compare building an internal payroll system with buying a dedicated platform across statutory maintenance, security, testing, integrations and ownership.",
    intro: "Building payroll software is not only a software-development decision. It creates an ongoing obligation to maintain payroll rules, security controls, auditability, integrations and production reliability.",
    proof: ["Engineering ownership", "Rule maintenance", "Security", "Testing", "Support", "Long-term cost"],
    sections: [
      { title: "Building creates permanent maintenance work", body: "Payroll rules, tax treatment, government contribution logic and workforce policies continue changing after the first release." },
      { title: "Security scope is larger than the payroll formula", body: "An internal system still needs authentication, authorization, session management, sensitive-data protection, backups, monitoring and incident handling." },
      { title: "Buying trades customization for operating leverage", body: "A dedicated platform spreads product, testing and maintenance work across a broader customer base while still requiring configuration for your payroll policies." },
      { title: "Use ownership as the deciding framework", body: "Build when payroll software itself is strategically important enough to justify a permanent engineering and compliance-maintenance capability." },
    ],
    related: [
      { label: "Developer center", href: "/developers", description: "Review where APIs can extend a purchased platform." },
      { label: "Security", href: "/security", description: "See the controls an internal build would also need to reproduce." },
      { label: "Buyer guide", href: "/resources/best-payroll-software-philippines", description: "Evaluate an existing platform before choosing to build." },
    ],
  },
];

export const industryWave2: AuthorityPage[] = [
  {
    slug: "retail",
    eyebrow: "Retail payroll Philippines",
    title: "Payroll and timekeeping for Philippine retail teams.",
    description: "Payroll software for retail businesses managing branches, shifts, overtime, holidays, attendance and employee payroll across multiple locations.",
    intro: "Retail payroll combines branch operations, variable schedules, weekend work, holidays and high employee movement. Payroll needs to preserve location and schedule context without making every cutoff a manual rebuild.",
    proof: ["Multi-branch hierarchy", "Shift scheduling", "Attendance processing", "Holiday premiums", "Employee self-service", "Role-based access"],
    sections: [
      { title: "Keep branch operations organized", body: "Multi-branch and department structures help scope employee, schedule and approval work without collapsing every store into one undifferentiated roster." },
      { title: "Handle changing schedules before payroll", body: "Time and attendance workflows can convert punches and schedules into payroll-relevant hours and exceptions." },
      { title: "Price holiday and overtime context", body: "Premium-pay logic uses the work date and schedule context rather than assuming every hour has the same multiplier." },
      { title: "Reduce payroll desk traffic", body: "Employee self-service gives workers direct access to released payslips and payroll history." },
    ],
    related: [
      { label: "Time & attendance", href: "/time-and-attendance", description: "See shift and attendance workflows." },
      { label: "Holiday pay calculator", href: "/calculators/holiday-pay", description: "Estimate premium pay for different day types." },
      { label: "Employee self-service", href: "/employee-self-service", description: "Review employee payroll access." },
    ],
  },
  {
    slug: "healthcare",
    eyebrow: "Healthcare payroll Philippines",
    title: "Payroll for Philippine healthcare teams with complex schedules.",
    description: "Payroll software for healthcare employers managing round-the-clock shifts, overtime, night differential, rest days and role-based payroll review.",
    intro: "Healthcare payroll often involves continuous staffing, night work, schedule changes and overtime. The payroll process needs to preserve worked-time context while keeping approvals controlled.",
    proof: ["Night differential", "Overtime", "Shift scheduling", "Rest-day history", "Attendance exceptions", "Approval separation"],
    sections: [
      { title: "Support round-the-clock work patterns", body: "Night work and overtime can be derived from attendance ranges instead of entered as one manual allowance." },
      { title: "Keep historical schedule context", body: "Effective-dated rest-day data helps historical payroll calculations use the schedule that applied at the time." },
      { title: "Surface attendance exceptions", body: "Incomplete or inconsistent punch data can be flagged for review before payroll release." },
      { title: "Separate preparation and approval", body: "Payroll staff can prepare calculations while checkers and owners retain review and release authority." },
    ],
    related: [
      { label: "Night differential calculator", href: "/calculators/night-differential", description: "Estimate night-work payroll impact." },
      { label: "Time & attendance", href: "/time-and-attendance", description: "See schedule and punch processing." },
      { label: "Security", href: "/security", description: "Review access controls for sensitive employee data." },
    ],
  },
  {
    slug: "hospitality",
    eyebrow: "Hospitality payroll Philippines",
    title: "Payroll for Philippine hotels, restaurants and hospitality teams.",
    description: "Payroll software for hospitality teams handling rotating shifts, holidays, night work, overtime, attendance and employee self-service.",
    intro: "Hospitality payroll is shaped by weekends, holidays, late shifts and changing staffing patterns. Linaw models those time conditions before payroll reaches review.",
    proof: ["Rotating schedules", "Night work", "Holiday premiums", "Overtime", "Attendance exceptions", "Payslip self-service"],
    sections: [
      { title: "Use schedule context throughout payroll", body: "Attendance and work schedules provide the context needed to price overtime, rest-day and holiday work." },
      { title: "Handle late and overnight shifts", body: "Night differential minutes can be derived from actual time ranges and combined with overtime context." },
      { title: "Review exceptions before payroll closes", body: "Incomplete punches and unusual attendance states can stay visible instead of being silently converted into assumptions." },
      { title: "Give employees direct payroll access", body: "Released payslips and year-to-date pay can be available through employee self-service." },
    ],
    related: [
      { label: "Time & attendance", href: "/time-and-attendance", description: "Review scheduling and attendance workflows." },
      { label: "Overtime calculator", href: "/calculators/overtime-pay", description: "Estimate overtime under different day conditions." },
      { label: "Employee self-service", href: "/employee-self-service", description: "See employee payroll access." },
    ],
  },
  {
    slug: "banking-finance",
    eyebrow: "Finance payroll Philippines",
    title: "Controlled payroll workflows for Philippine finance teams.",
    description: "Payroll software for finance organizations needing role separation, auditability, sensitive-data controls, payroll approvals and accounting outputs.",
    intro: "For finance-heavy organizations, payroll is not only a calculation problem. Review ownership, access boundaries, audit evidence and downstream accounting are equally important.",
    proof: ["Maker-checker roles", "Tenant and department scope", "Audit trail", "MFA", "Accounting exports", "Payroll release controls"],
    sections: [
      { title: "Separate maker, checker and release roles", body: "Preparation, independent review and final release can be represented as distinct responsibilities rather than one broad payroll permission." },
      { title: "Keep sensitive access scoped", body: "Tenant and department authorization controls reduce unnecessary access to payroll and employee records." },
      { title: "Preserve audit evidence", body: "Critical payroll and approval actions can be reconstructed through audit records rather than relying on email history." },
      { title: "Connect payroll close to finance outputs", body: "Released payroll can feed accounting exports and payout evidence without treating every downstream file as a native integration." },
    ],
    related: [
      { label: "Security", href: "/security", description: "Review authentication and authorization controls." },
      { label: "Trust center", href: "/trust", description: "See evidence-backed product claims." },
      { label: "Integrations", href: "/integrations", description: "Review accounting and payroll interfaces." },
    ],
  },
  {
    slug: "education",
    eyebrow: "Education payroll Philippines",
    title: "Payroll for Philippine schools and education organizations.",
    description: "Payroll software for schools and education organizations managing multiple employee groups, schedules, deductions, benefits and payroll review.",
    intro: "Education payroll can involve teaching and non-teaching groups, different schedules, recurring benefits, loans and administrative approval structures.",
    proof: ["Employee groups", "Schedules", "Benefits", "Loans and deductions", "Role-based approvals", "Employee payslips"],
    sections: [
      { title: "Manage different employee groups in one system", body: "Employee records, department scope and payroll configuration help separate operational groups without requiring a different payroll platform for each." },
      { title: "Connect recurring payroll items", body: "Benefits, loans and other payroll-impacting items can be represented alongside the employee and payroll record." },
      { title: "Use structured approvals", body: "Payroll preparation and review can follow defined roles rather than informal spreadsheet handoffs." },
      { title: "Give employees direct access to released pay information", body: "Self-service can reduce repeated requests for payslip copies and payroll history." },
    ],
    related: [
      { label: "HRIS", href: "/hris", description: "Review employee records and organizational structure." },
      { label: "Employee self-service", href: "/employee-self-service", description: "See employee payroll access." },
      { label: "Implementation", href: "/implementation", description: "Plan migration across multiple employee groups." },
    ],
  },
];
