import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";

const read = (path: string) => readFileSync(path, "utf8");

test("0069 adds generated-document provenance and organization-scoped idempotency", () => {
  const migration = read("drizzle/0069_automation_generated_document_provenance.sql");
  assert.ok(migration.includes('"source_type" varchar(24) NOT NULL DEFAULT \'upload\''));
  assert.ok(migration.includes('"source_key" varchar(160)'));
  assert.ok(migration.includes('"generation_metadata" jsonb'));
  assert.ok(migration.includes("documents_org_source_key_unique"));
  assert.ok(migration.includes("WHERE \"source_key\" IS NOT NULL"));
  assert.ok(migration.includes("'upload','generated'"));
});

test("fresh schema mirrors generated-document provenance constraints", () => {
  const schema = read("src/db/schema.ts");
  const baseline = read("drizzle/baseline.sql");
  for (const source of [schema, baseline]) {
    assert.ok(source.includes("source_type"));
    assert.ok(source.includes("source_key"));
    assert.ok(source.includes("generation_metadata"));
    assert.ok(source.includes("documents_org_source_key_unique"));
  }
  assert.ok(schema.includes("documents_source_type_check"));
});

test("generated document templates are server-owned, versioned, and trigger bounded", () => {
  const source = read("src/lib/automation-document-templates.ts");
  for (const id of [
    "employee-onboarding-summary",
    "employee-movement-notice",
    "employee-separation-handoff-summary",
  ]) {
    assert.ok(source.includes(`id: "${id}"`), `missing generated document template ${id}`);
  }
  assert.ok(source.includes("version: 1"));
  assert.ok(source.includes('allowedTriggers: ["employee.hired"]'));
  assert.ok(source.includes('"employee.moved", "employee.promoted"'));
  assert.ok(source.includes('allowedTriggers: ["employee.separated"]'));
  assert.ok(source.includes("does not replace a signed employment contract"));
});

test("Automation Studio generated documents require an immediately preceding approval gate", () => {
  const engine = read("src/lib/automation.ts");
  assert.ok(engine.includes('type: "generate_document"'));
  assert.ok(engine.includes('label: "Generate employee document"'));
  assert.ok(engine.includes("Generated-document template is not approved for this trigger."));
  assert.ok(engine.includes("Document generation must be immediately preceded by an approval gate."));
});

test("document generation is employee scoped, idempotent, and immutable by source key", () => {
  const helper = read("src/lib/automation-document-generation.ts");
  assert.ok(helper.includes("eq(documents.sourceKey, sourceKey)"));
  assert.ok(helper.includes('sourceType: "generated"'));
  assert.ok(helper.includes("onConflictDoNothing().returning()"));
  assert.ok(helper.includes("document.sha256 !== sha256"));
  assert.ok(helper.includes("Generated-document idempotency conflict detected"));
  assert.ok(helper.includes("Employee document generated by governed automation"));
});

test("generated artifacts explicitly distinguish system generation from uploaded malware scanning", () => {
  const helper = read("src/lib/automation-document-generation.ts");
  assert.ok(helper.includes("System-generated by PayrollPH from a governed template; no uploaded bytes were accepted."));
  assert.ok(helper.includes('mimeType: "text/plain; charset=utf-8"'));
  assert.ok(helper.includes("scannedClean: true"));
});

test("document download hash-verifies generated artifacts before serving", () => {
  const route = read("src/app/api/documents/[id]/route.ts");
  assert.ok(route.includes('document.sourceType === "generated"'));
  assert.ok(route.includes('createHash("sha256").update(body).digest("hex")'));
  assert.ok(route.includes("Generated document integrity verification failed."));
});

test("document listings expose provenance without exposing stored content", () => {
  const route = read("src/app/api/documents/route.ts");
  assert.ok(route.includes("sourceType: documents.sourceType"));
  assert.ok(route.includes("generationMetadata: documents.generationMetadata"));
  const getSection = route.slice(0, route.indexOf("export async function POST"));
  assert.equal(getSection.includes("content: documents.content"), false);
});

test("Automation Studio API exposes safe generated-document template metadata only", () => {
  const route = read("src/app/api/automation-studio/route.ts");
  const start = route.indexOf("documentTemplates: AUTOMATION_DOCUMENT_TEMPLATES.map");
  const end = route.indexOf("templates: AUTOMATION_WORKFLOW_TEMPLATES.map", start);
  const block = route.slice(start, end);
  assert.ok(block.includes("id: template.id"));
  assert.ok(block.includes("version: template.version"));
  assert.ok(block.includes("allowedTriggers"));
  assert.equal(block.includes("render: template.render"), false);
});

test("Automation Studio builder requires approval adjacency and compatible template selection", () => {
  const ui = read("src/components/automation-studio-panel.tsx");
  assert.ok(ui.includes('row.type === "generate_document" && actions[index - 1]?.type !== "approval_gate"'));
  assert.ok(ui.includes("Document generation must be immediately preceded by an approval gate."));
  assert.ok(ui.includes("Choose approved document template"));
  assert.ok(ui.includes("template.allowedTriggers.includes(selectedTrigger?.value ?? \"\")"));
  assert.ok(ui.includes("does not replace signed contracts, statutory notices, legal advice, or employee acknowledgement"));
});

test("automation execution evidence retains generated document identity and hash", () => {
  const engine = read("src/lib/automation.ts");
  assert.ok(engine.includes("generateAutomationEmployeeDocument"));
  assert.ok(engine.includes("Automation Studio document #"));
  assert.ok(engine.includes("documentId: result.document.id"));
  assert.ok(engine.includes("sha256: result.document.sha256"));
  assert.ok(engine.includes("templateVersion: template.version"));
});
