import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import {
  bankFileSha256,
  parseBankPortalOutcome,
} from "../src/lib/bank-evidence-store";

test("bank file evidence hashes the exact generated bytes deterministically", () => {
  assert.equal(
    bankFileSha256("payroll\nrow\n"),
    bankFileSha256("payroll\nrow\n"),
  );
  assert.notEqual(
    bankFileSha256("payroll\nrow\n"),
    bankFileSha256("payroll\nrow 2\n"),
  );
});

test("accepted bank UAT requires a portal reference and rejected UAT requires a bank note", () => {
  assert.equal(parseBankPortalOutcome({ outcome: "accepted" }).ok, false);
  assert.equal(parseBankPortalOutcome({
    outcome: "accepted",
    portalReference: "BATCH-1234",
    submittedAt: "2026-10-03T08:00:00Z",
  }).ok, true);

  assert.equal(parseBankPortalOutcome({ outcome: "rejected" }).ok, false);
  assert.equal(parseBankPortalOutcome({
    outcome: "rejected",
    note: "Invalid bank upload column format",
  }).ok, true);
});

test("bank validation outcome is owner-only, MFA protected, rate-limited and immutable", () => {
  const source = readFileSync("src/app/api/compliance/bank-validations/[id]/route.ts", "utf8");
  assert.ok(source.includes("PAYROLL_DISBURSEMENT_ROLES"));
  assert.ok(source.includes("requireSensitiveActionMfa"));
  assert.ok(source.includes("enforceSensitiveActionRateLimit"));
  assert.ok(source.includes('existing.status !== "generated"'));
  assert.ok(source.includes("is immutable"));
});

test("bank UAT stores only file identity/evidence, not the payroll file contents", () => {
  const schema = readFileSync("src/db/schema.ts", "utf8");
  const store = readFileSync("src/lib/bank-evidence-store.ts", "utf8");
  assert.ok(schema.includes('bankFileValidations = pgTable('));
  assert.ok(schema.includes('fileSha256: varchar("file_sha256"'));
  assert.ok(!schema.includes('bank_file_validations", {\n    fileContent'));
  assert.ok(store.includes("generateBankFile"));
  assert.ok(store.includes("fileSha256"));
  assert.ok(!store.includes("fileContent"));
});

test("manual corporate bank acceptance can satisfy bank readiness but generation alone cannot", () => {
  const readiness = readFileSync("src/app/api/readiness/route.ts", "utf8");
  assert.ok(readiness.includes("acceptedBankFileValidationCount"));
  assert.ok(readiness.includes("manualBankUatProven = acceptedBankFileValidations > 0"));
  assert.ok(readiness.includes("recorded corporate-portal acceptance evidence"));
  assert.ok(readiness.includes("/api/compliance/bank-validations"));
});

test("production compatibility creates the bank validation evidence table", () => {
  const compat = readFileSync("src/lib/core-schema-compat.ts", "utf8");
  assert.match(compat, /linaw_core_schema_compat_v\d+/);
  assert.ok(compat.includes("CREATE TABLE IF NOT EXISTS bank_file_validations"));
  assert.ok(compat.includes("bank_file_validation_unique"));
  assert.ok(compat.includes("bank_file_validations_status_check"));
});


test("manual payout completion requires accepted UAT for the exact bank template version", () => {
  const route = readFileSync("src/app/api/payroll-runs/[id]/exports/route.ts", "utf8");
  assert.ok(route.includes("acceptedTemplateValidation"));
  assert.ok(route.includes("bankFileValidations.templateName"));
  assert.ok(route.includes("bankFileValidations.templateVersion"));
  assert.ok(route.includes('bankFileValidations.status, "accepted"'));
  assert.ok(route.includes("has not passed recorded bank-portal UAT"));
});

test("RCBC export uses an explicit bank-provided mapping and never guesses a proprietary layout", () => {
  const exporter = readFileSync("src/lib/exporters.ts", "utf8");
  const engine = readFileSync("src/lib/payroll-engine.ts", "utf8");
  assert.ok(exporter.includes('tName.includes("rcbc")'));
  assert.ok(exporter.includes("readDelimitedBankMapping(template.mappings)"));
  assert.ok(exporter.includes("PayrollPH will not guess a proprietary upload layout"));
  assert.ok(exporter.includes("renderMappedBankRows"));
  assert.ok(engine.includes("firstName: employee.firstName"));
  assert.ok(engine.includes("middleName: employee.middleName"));
  assert.ok(engine.includes("lastName: employee.lastName"));
  assert.ok(engine.includes("email: employee.email"));
});
