"use client";

import { useState } from "react";
import {
  AlertTriangle,
  Banknote,
  BookOpen,
  Building2,
  Database,
  Download,
  FileSpreadsheet,
  Info,
  ShieldCheck,
  Users,
} from "lucide-react";
import type { DashboardData, Notify } from "./types";
import { derivePayrollPostReleaseStatus } from "@/lib/payroll-post-release";
import { EmptyState, PageHeading, Segmented, Status, formatDate, money } from "./ui";

const GOVERNMENT_DRAFTS = [
  { template: "1601-C", detail: "Monthly remittance return of income taxes withheld on compensation" },
  { template: "Alphalist/2316", detail: "Year-end alphalist and certificate of compensation summary" },
  { template: "SSS R-3", detail: "Monthly contribution collection list, recomputed from the full monthly MSC" },
  { template: "PhilHealth RF-1", detail: "Employer remittance report" },
  { template: "Pag-IBIG MCRF", detail: "Membership contribution remittance form" },
];

export function ExportsView({
  data,
  notify,
  onRefresh,
}: {
  data: DashboardData;
  notify: Notify;
  onRefresh: () => Promise<void>;
}) {
  const runs = data.payrollRuns;
  const [runId, setRunId] = useState<number | undefined>(runs[0]?.id);
  const [template, setTemplate] = useState(data.templates[0]?.name ?? "BDO DAT");
  const [mode, setMode] = useState<"dry" | "live">("dry");
  const [exportFailure, setExportFailure] = useState<{ url: string; label: string; error: string } | null>(null);
  const [exporting, setExporting] = useState<string | null>(null);
  const [confirmingUpload, setConfirmingUpload] = useState(false);
  const [payoutBusy, setPayoutBusy] = useState(false);

  const run = runs.find((item) => item.id === runId) ?? runs[0];
  const organizationId = data.selectedOrganization.id;
  const postReleaseStatus = run ? derivePayrollPostReleaseStatus(run, data.auditEvents) : null;

  async function download(url: string, label: string) {
    setExporting(label);
    try {
      const response = await fetch(url, { cache: "no-store" });
      if (!response.ok) {
        const payload = await response.json().catch(() => ({}));
        const error = payload.error ?? `${label} failed with status ${response.status}.`;
        setExportFailure({ url, label, error });
        notify(error, "err");
        return;
      }
      const blob = await response.blob();
      const disposition = response.headers.get("content-disposition") ?? "";
      const filename = disposition.match(/filename="?([^";]+)"?/i)?.[1] ?? label.replace(/\s+/g, "-").toLowerCase();
      const href = URL.createObjectURL(blob);
      const anchor = document.createElement("a");
      anchor.href = href;
      anchor.download = filename;
      document.body.appendChild(anchor);
      anchor.click();
      anchor.remove();
      URL.revokeObjectURL(href);
      setExportFailure(null);
      if (url.includes("kind=bank") && url.includes("dryRun=false")) {
        await onRefresh();
      }
      notify(`${label} generated and written to the audit trail.`, "info");
    } catch {
      const error = `${label} could not be generated because the export service could not be reached.`;
      setExportFailure({ url, label, error });
      notify(error, "err");
    } finally {
      setExporting(null);
    }
  }

  async function confirmBankUpload() {
    if (!run) return;
    setPayoutBusy(true);
    try {
      const response = await fetch(`/api/payroll-runs/${run.id}/payout-confirmation`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ confirm: true }),
      });
      const payload = await response.json().catch(() => ({}));
      if (!response.ok) {
        notify(payload.error ?? "Bank upload confirmation could not be recorded.", "err");
        return;
      }
      await onRefresh();
      setConfirmingUpload(false);
      notify(payload.message ?? "Bank upload recorded.", "info");
    } catch {
      notify("Could not reach the payout confirmation service.", "err");
    } finally {
      setPayoutBusy(false);
    }
  }

  return (
    <>
      <PageHeading
        eyebrow="Exports"
        title="Files that leave a paper trail."
        copy="Every export is generated by the API from stored payroll rows, tagged with its template version, and recorded as an audit event attributed to you."
      />

      <div className="notice notice-blue">
        <Info size={15} className="i-blue" />
        <span>
          Linaw generates these files; it does not submit them. There is no live bank host-to-host or certified government
          filing connection in this deployment, see <a className="link-button" href="/api/readiness">/api/readiness</a> for
          the gate-by-gate status.
        </span>
      </div>
      {run?.status === "Released" && postReleaseStatus && (
        <article className="card" data-post-release-payout style={{ marginTop: 16, marginBottom: 16 }}>
          <div className="card-header">
            <div>
              <div className="card-kicker">POST-RELEASE PAYOUT</div>
              <h2>{postReleaseStatus.label}</h2>
              <p>{postReleaseStatus.detail}</p>
            </div>
            <Status value={postReleaseStatus.state === "disbursed" ? "Disbursed" : postReleaseStatus.state === "submitted" ? "Submitted" : postReleaseStatus.state === "exported" ? "File generated" : "Ready"} />
          </div>
          <div className="card-body" style={{ paddingTop: 0, display: "grid", gap: 8 }}>
            <div className="exception-row">
              <span className="status status-approved" style={{ minWidth: 84, justifyContent: "center" }}>Released</span>
              <div><strong>Payroll locked</strong><p>The approved register and employee payslips are final for this run.</p></div>
            </div>
            <div className="exception-row">
              <span className={`status ${postReleaseStatus.state !== "released" ? "status-approved" : "status-review"}`} style={{ minWidth: 84, justifyContent: "center" }}>
                {postReleaseStatus.state !== "released" ? "Generated" : "Pending"}
              </span>
              <div>
                <strong>Final bank file</strong>
                <p>{postReleaseStatus.bankFilename ? `${postReleaseStatus.bankFilename} is recorded for this exact run.` : "Generate a non-dry-run bank file before external submission."}</p>
              </div>
            </div>
            <div className="exception-row">
              <span className={`status ${postReleaseStatus.state === "submitted" || postReleaseStatus.state === "disbursed" ? "status-approved" : "status-review"}`} style={{ minWidth: 84, justifyContent: "center" }}>
                {postReleaseStatus.state === "disbursed" ? "Disbursed" : postReleaseStatus.state === "submitted" ? "Submitted" : "Pending"}
              </span>
              <div>
                <strong>Payout handoff</strong>
                <p>{postReleaseStatus.state === "submitted" ? "Submitted externally; final settlement is not independently verified." : postReleaseStatus.detail}</p>
              </div>
              {postReleaseStatus.state === "exported" && (
                <button className="secondary-button" onClick={() => setConfirmingUpload(true)}>Record bank upload</button>
              )}
            </div>
            {confirmingUpload && postReleaseStatus.state === "exported" && (
              <div className="notice notice-amber">
                <AlertTriangle size={15} className="i-red" />
                <div style={{ flex: 1 }}>
                  <strong>Confirm only after external upload</strong>
                  <p style={{ margin: "4px 0 0" }}>This records submission to the bank portal. It does not mark employee payments as settled.</p>
                </div>
                <button className="secondary-button" disabled={payoutBusy} onClick={() => setConfirmingUpload(false)}>Cancel</button>
                <button className="primary-button" disabled={payoutBusy} onClick={() => void confirmBankUpload()}>
                  {payoutBusy ? "Recording…" : "Confirm uploaded"}
                </button>
              </div>
            )}
          </div>
        </article>
      )}

      {exportFailure && (
        <div className="notice notice-red" data-recovery-state="export-failed" style={{ marginTop: 12 }}>
          <AlertTriangle size={15} className="i-red" />
          <div style={{ flex: 1 }}>
            <strong>Export failed</strong>
            <p style={{ margin: "4px 0 0" }}>{exportFailure.error}</p>
          </div>
          <button className="secondary-button" disabled={Boolean(exporting)} onClick={() => void download(exportFailure.url, exportFailure.label)}>
            {exporting ? "Retrying…" : "Retry export"}
          </button>
        </div>
      )}

      {!run ? (
        <article className="card">
          <EmptyState icon={<FileSpreadsheet size={22} className="i-teal" />} title="No payroll runs to export">
            Bank files, journals and worksheets are all derived from a calculated run. Create and calculate one first.
          </EmptyState>
        </article>
      ) : (
        <>
          <article className="card" style={{ marginBottom: 16 }}>
            <div className="card-header">
              <div>
                <div className="card-kicker">Source run</div>
                <h2>Which run are we exporting?</h2>
                <p>Bank, journal and worksheet exports all read this run&apos;s stored entries.</p>
              </div>
              <Status value={run.status} />
            </div>
            <div className="setting-form">
              <label>
                Payroll run
                <select value={run.id} onChange={(event) => setRunId(Number(event.target.value))}>
                  {runs.map((item) => (
                    <option key={item.id} value={item.id}>
                      {item.periodLabel} · {item.scopeLabel} · {item.status}
                    </option>
                  ))}
                </select>
              </label>
              <label>
                Pay date
                <input value={formatDate(run.payDate)} readOnly />
              </label>
            </div>
            <div className="run-stats" style={{ marginTop: 0 }}>
              <div>
                <span>Employees</span>
                <strong>{run.employeeCount}</strong>
              </div>
              <div>
                <span>Gross</span>
                <strong>{money(run.grossPay)}</strong>
              </div>
              <div>
                <span>Net to disburse</span>
                <strong className="green-number">{money(run.netPay)}</strong>
              </div>
            </div>
          </article>

          <section className="integration-grid">
            <article className="export-card">
              <span className="inline-icon blue" aria-hidden>
                <Building2 size={16} />
              </span>
              <div>
                <h3>
                  Bank disbursement <Status value="Versioned" />
                </h3>
                <p>
                  Generators for BDO DAT and BPI / UnionBank / GCash CSV. Validate first, a dry run checks every row
                  without producing a file that looks submittable.
                </p>
                <div style={{ display: "grid", gap: 10, marginTop: 12 }}>
                  <label className="field">
                    <span>Template</span>
                    <select value={template} onChange={(event) => setTemplate(event.target.value)}>
                      {(data.templates.length ? data.templates : [{ id: 0, name: "BDO DAT", version: "", format: "" }]).map(
                        (item) => (
                          <option key={item.id} value={item.name}>
                            {item.name}
                            {item.version ? ` · ${item.version}` : ""}
                          </option>
                        ),
                      )}
                    </select>
                  </label>
                  <Segmented
                    label="Bank export mode"
                    value={mode}
                    onChange={setMode}
                    options={[
                      { value: "dry", label: "Validate" },
                      { value: "live", label: "Generate file" },
                    ]}
                  />
                  <button
                    className={mode === "live" ? "primary-button" : "secondary-button"}
                    onClick={() =>
                      void download(
                        `/api/payroll-runs/${run.id}/exports?kind=bank&template=${encodeURIComponent(template)}&dryRun=${mode === "dry"}`,
                        mode === "dry" ? `${template} validation` : `${template} disbursement file`,
                      )
                    }
                  >
                    <Download size={14} className="i-teal" /> {mode === "dry" ? "Run validation" : `Generate ${template}`}
                  </button>
                </div>
              </div>
            </article>

            <article className="export-card">
              <span className="inline-icon purple" aria-hidden>
                <BookOpen size={16} />
              </span>
              <div>
                <h3>
                  Accounting journal <Status value="Ready" />
                </h3>
                <p>Journal CSV for Xero and QuickBooks Online, balanced against this run&apos;s gross, deductions and net.</p>
                <button
                  className="secondary-button"
                  style={{ marginTop: 12 }}
                  onClick={() => void download(`/api/payroll-runs/${run.id}/exports?kind=journal`, "Journal CSV")}
                >
                  <Download size={14} className="i-teal" /> Journal CSV
                </button>
              </div>
            </article>

            <article className="export-card">
              <span className="inline-icon amber" aria-hidden>
                <ShieldCheck size={16} />
              </span>
              <div>
                <h3>
                  Government worksheets <Status value="Draft only" />
                </h3>
                <p>
                  Computed from the same rule engine as payroll, but <strong>not</strong> byte-validated against the
                  agencies&apos; own import tools. Every file is labelled DRAFT.
                </p>
                <div className="worksheet-list" style={{ padding: "12px 0 0" }}>
                  {GOVERNMENT_DRAFTS.map((item) => (
                    <div className="leave-request" key={item.template} style={{ padding: "10px 12px" }}>
                      <div>
                        <strong>{item.template}</strong>
                        <p>{item.detail}</p>
                      </div>
                      <button
                        className="secondary-button"
                        style={{ height: 28, fontSize: 11 }}
                        onClick={() =>
                      void download(
                            `/api/payroll-runs/${run.id}/exports?kind=government&template=${encodeURIComponent(item.template)}`,
                            `${item.template} draft`,
                          )
                        }
                      >
                        <Download size={13} className="i-teal" /> Draft
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            </article>

            <article className="export-card">
              <span className="inline-icon green" aria-hidden>
                <Banknote size={16} />
              </span>
              <div>
                <h3>Payslip PDFs</h3>
                <p>
                  One PDF per released entry, written by the built-in generator with no PDF dependency. Available once the
                  run is released.
                </p>
                <button
                  className="secondary-button"
                  style={{ marginTop: 12 }}
                  disabled={run.status !== "Released"}
                  onClick={() => void download(`/api/payroll-runs/${run.id}/exports?kind=payslip`, "Payslip index")}
                >
                  <Download size={14} className="i-teal" /> List payslips
                </button>
              </div>
            </article>

            <article className="export-card">
              <span className="inline-icon slate" aria-hidden>
                <Users size={16} />
              </span>
              <div>
                <h3>Employee roster</h3>
                <p>The full directory as CSV, the same column set the bulk importer accepts back.</p>
                <button
                  className="secondary-button"
                  style={{ marginTop: 12 }}
                  onClick={() => void download(`/api/exports?organizationId=${organizationId}&kind=employees`, "Employee roster CSV")}
                >
                  <Download size={14} className="i-teal" /> employees.csv
                </button>
              </div>
            </article>

            <article className="export-card">
              <span className="inline-icon slate" aria-hidden>
                <Database size={16} />
              </span>
              <div>
                <h3>Full company export</h3>
                <p>
                  Data-portability JSON covering the organization, people, runs and audit events, the Data Privacy Act
                  portability path.
                </p>
                <div style={{ display: "flex", gap: 8, marginTop: 12, flexWrap: "wrap" }}>
                  <button
                    className="secondary-button"
                    onClick={() => void download(`/api/exports?organizationId=${organizationId}&kind=all`, "Full JSON export")}
                  >
                    <Download size={14} className="i-teal" /> JSON
                  </button>
                  <button
                    className="secondary-button"
                    onClick={() => void download(`/api/exports?organizationId=${organizationId}&kind=audit`, "Audit trail CSV")}
                  >
                    <Download size={14} className="i-teal" /> Audit CSV
                  </button>
                </div>
              </div>
            </article>
          </section>
        </>
      )}
    </>
  );
}
