"use client";

import { useState } from "react";
import {
  Banknote,
  BookOpen,
  Building2,
  Database,
  Download,
  FileSpreadsheet,
  Info,
  ShieldCheck,
  Users,
} from "lucide-react";
import type { DashboardData, Notify } from "./types";
import { EmptyState, PageHeading, Segmented, Status, formatDate, money } from "./ui";

const GOVERNMENT_WORKSHEETS = [
  { value: "bir-1601c", label: "BIR 1601-C worksheet", detail: "Cutoff withholding summary. This is not the filed return." },
  { value: "bir-1604c-source", label: "BIR 1604-C annual source extract", detail: "Source fields for year-end work. Exact DAT generation stays disabled until the annual schedule is complete and passes BIR Alphalist v7.4." },
  { value: "sss-r3", label: "SSS e-CL / R-3 worksheet", detail: "Full-month SSS and EC amounts for My.SSS e-CL / R-3 review. PRN and employer-portal acceptance are still required." },
  { value: "philhealth-rf1", label: "PhilHealth EPRS / RF-1 worksheet", detail: "Full-month premium worksheet for the mandatory employer EPRS workflow." },
  { value: "pagibig-mcrf", label: "Pag-IBIG MCRF / eSRS worksheet", detail: "Assisted contribution worksheet only. The prescribed spreadsheet/eSRS format is not claimed as upload-ready." },
];

export function ExportsView({ data, notify }: { data: DashboardData; notify: Notify }) {
  const runs = data.payrollRuns;
  const [runId, setRunId] = useState<number | undefined>(runs[0]?.id);
  const [template, setTemplate] = useState(data.templates[0]?.name ?? "BDO DAT");
  const [mode, setMode] = useState<"dry" | "live">("dry");

  const run = runs.find((item) => item.id === runId) ?? runs[0];
  const organizationId = data.selectedOrganization.id;

  function download(url: string, label: string) {
    window.open(url, "_blank", "noopener");
    notify(`${label} requested, generated server-side and written to the audit trail.`, "info");
  }

  return (
    <>
      <PageHeading
        eyebrow="Exports"
        title="Files that leave a paper trail."
        copy="Every export is generated by the API from stored payroll rows, tagged with its template version, and recorded as an audit event attributed to you."
      />

      <div className="notice notice-blue">
        <Info size={15} className="i-blue" />
        <span>
          Linaw generates these files; it does not submit them. There is no live bank host-to-host or certified government
          filing connection in this deployment, see <a className="link-button" href="/api/readiness">/api/readiness</a> for
          the gate-by-gate status.
        </span>
      </div>

      {!run ? (
        <article className="card">
          <EmptyState icon={<FileSpreadsheet size={22} className="i-teal" />} title="No payroll runs to export">
            Bank files, journals and worksheets are all derived from a calculated run. Create and calculate one first.
          </EmptyState>
        </article>
      ) : (
        <>
          <article className="card" style={{ marginBottom: 16 }}>
            <div className="card-header">
              <div>
                <div className="card-kicker">Source run</div>
                <h2>Which run are we exporting?</h2>
                <p>Bank, journal and worksheet exports all read this run&apos;s stored entries.</p>
              </div>
              <Status value={run.status} />
            </div>
            <div className="setting-form">
              <label>
                Payroll run
                <select value={run.id} onChange={(event) => setRunId(Number(event.target.value))}>
                  {runs.map((item) => (
                    <option key={item.id} value={item.id}>
                      {item.periodLabel} · {item.scopeLabel} · {item.status}
                    </option>
                  ))}
                </select>
              </label>
              <label>
                Pay date
                <input value={formatDate(run.payDate)} readOnly />
              </label>
            </div>
            <div className="run-stats" style={{ marginTop: 0 }}>
              <div>
                <span>Employees</span>
                <strong>{run.employeeCount}</strong>
              </div>
              <div>
                <span>Gross</span>
                <strong>{money(run.grossPay)}</strong>
              </div>
              <div>
                <span>Net to disburse</span>
                <strong className="green-number">{money(run.netPay)}</strong>
              </div>
            </div>
          </article>

          <section className="integration-grid">
            <article className="export-card">
              <span className="inline-icon blue" aria-hidden>
                <Building2 size={16} />
              </span>
              <div>
                <h3>
                  Bank disbursement <Status value="Versioned" />
                </h3>
                <p>
                  Generators for BDO DAT and BPI / UnionBank / GCash CSV. Validate first, a dry run checks every row
                  without producing a file that looks submittable.
                </p>
                <div style={{ display: "grid", gap: 10, marginTop: 12 }}>
                  <label className="field">
                    <span>Template</span>
                    <select value={template} onChange={(event) => setTemplate(event.target.value)}>
                      {(data.templates.length ? data.templates : [{ id: 0, name: "BDO DAT", version: "", format: "" }]).map(
                        (item) => (
                          <option key={item.id} value={item.name}>
                            {item.name}
                            {item.version ? ` · ${item.version}` : ""}
                          </option>
                        ),
                      )}
                    </select>
                  </label>
                  <Segmented
                    label="Bank export mode"
                    value={mode}
                    onChange={setMode}
                    options={[
                      { value: "dry", label: "Validate" },
                      { value: "live", label: "Generate file" },
                    ]}
                  />
                  <button
                    className={mode === "live" ? "primary-button" : "secondary-button"}
                    disabled={mode === "live" && run.status !== "Released"}
                    onClick={() =>
                      download(
                        `/api/payroll-runs/${run.id}/exports?kind=bank&template=${encodeURIComponent(template)}&dryRun=${mode === "dry"}`,
                        mode === "dry" ? `${template} validation` : `${template} disbursement file`,
                      )
                    }
                  >
                    <Download size={14} className="i-teal" /> {mode === "dry"
                      ? "Run validation"
                      : run.status === "Released"
                        ? `Generate ${template}`
                        : "Release payroll first"}
                  </button>
                </div>
              </div>
            </article>

            <article className="export-card">
              <span className="inline-icon purple" aria-hidden>
                <BookOpen size={16} />
              </span>
              <div>
                <h3>
                  Accounting journal <Status value="Ready" />
                </h3>
                <p>Journal CSV for Xero and QuickBooks Online, balanced against this run&apos;s gross, deductions and net.</p>
                <button
                  className="secondary-button"
                  style={{ marginTop: 12 }}
                  onClick={() => download(`/api/payroll-runs/${run.id}/exports?kind=journal`, "Journal CSV")}
                >
                  <Download size={14} className="i-teal" /> Journal CSV
                </button>
              </div>
            </article>

            <article className="export-card">
              <span className="inline-icon amber" aria-hidden>
                <ShieldCheck size={16} />
              </span>
              <div>
                <h3>
                  Government worksheets <Status value="Draft only" />
                </h3>
                <p>
                  These are deliberately scoped to what Linaw can prove. BIR DAT, SSS/My.SSS, PhilHealth EPRS and
                  Pag-IBIG eSRS are not called filing-ready until the current agency workflow accepts them.
                </p>
                <div className="worksheet-list" style={{ padding: "12px 0 0" }}>
                  {GOVERNMENT_WORKSHEETS.map((item) => (
                    <div className="leave-request" key={item.value} style={{ padding: "10px 12px" }}>
                      <div>
                        <strong>{item.label}</strong>
                        <p>{item.detail}</p>
                      </div>
                      <button
                        className="secondary-button"
                        style={{ height: 28, fontSize: 11 }}
                        onClick={() =>
                          download(
                            `/api/payroll-runs/${run.id}/exports?kind=government&template=${encodeURIComponent(item.value)}`,
                            `${item.label} worksheet`,
                          )
                        }
                      >
                        <Download size={13} className="i-teal" /> Worksheet
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            </article>

            <article className="export-card">
              <span className="inline-icon green" aria-hidden>
                <Banknote size={16} />
              </span>
              <div>
                <h3>Payslip PDFs</h3>
                <p>
                  One PDF per released entry, written by the built-in generator with no PDF dependency. Available once the
                  run is released.
                </p>
                <button
                  className="secondary-button"
                  style={{ marginTop: 12 }}
                  disabled={run.status !== "Released"}
                  onClick={() => download(`/api/payroll-runs/${run.id}/exports?kind=payslip`, "Payslip index")}
                >
                  <Download size={14} className="i-teal" /> List payslips
                </button>
              </div>
            </article>

            <article className="export-card">
              <span className="inline-icon slate" aria-hidden>
                <Users size={16} />
              </span>
              <div>
                <h3>Employee roster</h3>
                <p>The full directory as CSV, the same column set the bulk importer accepts back.</p>
                <button
                  className="secondary-button"
                  style={{ marginTop: 12 }}
                  onClick={() => download(`/api/exports?organizationId=${organizationId}&kind=employees`, "Employee roster CSV")}
                >
                  <Download size={14} className="i-teal" /> employees.csv
                </button>
              </div>
            </article>

            <article className="export-card">
              <span className="inline-icon slate" aria-hidden>
                <Database size={16} />
              </span>
              <div>
                <h3>Full company export</h3>
                <p>
                  Data-portability JSON covering the organization, people, runs and audit events, the Data Privacy Act
                  portability path.
                </p>
                <div style={{ display: "flex", gap: 8, marginTop: 12, flexWrap: "wrap" }}>
                  <button
                    className="secondary-button"
                    onClick={() => download(`/api/exports?organizationId=${organizationId}&kind=all`, "Full JSON export")}
                  >
                    <Download size={14} className="i-teal" /> JSON
                  </button>
                  <button
                    className="secondary-button"
                    onClick={() => download(`/api/exports?organizationId=${organizationId}&kind=audit`, "Audit trail CSV")}
                  >
                    <Download size={14} className="i-teal" /> Audit CSV
                  </button>
                </div>
              </div>
            </article>
          </section>
        </>
      )}
    </>
  );
}
