import type { Metadata } from "next";
import {
  BadgeCheck,
  CircleAlert,
  FileCheck2,
  KeyRound,
  LockKeyhole,
  Network,
  ShieldCheck,
} from "lucide-react";
import { SiteFooter, SiteNav } from "@/components/marketing/site-chrome";

export const metadata: Metadata = {
  title: "Trust Center | Linaw Philippine Payroll",
  description: "Linaw security, privacy, payroll assurance, and external-attestation status, stated without inflating what has not yet been independently certified.",
  alternates: { canonical: "/trust" },
};

const implemented = [
  ["Tenant isolation", "Workspace membership and resource ownership are enforced server-side, with cross-tenant regression tests."],
  ["Authentication", "scrypt password hashing, durable lockout, revocable server sessions, distributed rate limits, TOTP and backup codes."],
  ["Sensitive-data encryption", "Employee payout accounts, government identifiers, TOTP secrets and configured SSO client secrets use authenticated encryption at rest."],
  ["Payroll segregation of duties", "Preparation, checker approval, release and live disbursement are separate permissions with audit evidence."],
  ["Filing and payout evidence", "Government and bank files are hash-bound to the exact generated bytes; acceptance is recorded separately from generation."],
  ["Data privacy workflows", "Access, correction, deletion, objection and portability requests are tracked with due dates and audit events."],
];

const external = [
  ["ISO/IEC 27001 certification", "Not certified", "No ISO certificate is claimed. Certification requires an independent audit of the organization and ISMS, not just secure application code."],
  ["SOC 2 Type II", "Not attested", "No SOC 2 report is claimed. A Type II report requires an independent auditor and an operating-period evidence window."],
  ["Independent penetration test", "External evidence pending", "Automated security testing and CodeQL do not substitute for an independent penetration-test report."],
  ["Government portal certification", "Per-format evidence required", "Linaw labels unvalidated filing outputs as DRAFT and records agency acceptance separately."],
  ["Bank upload certification", "Per-bank UAT required", "A generated bank file is not called upload-ready until the exact layout/version has accepted portal UAT evidence."],
];

export default function TrustPage() {
  return (
    <main className="min-h-screen bg-[#F8F9FC] text-[#11141F]">
      <SiteNav />
      <section className="border-b border-[#E6E8F0] bg-white">
        <div className="mx-auto max-w-[1160px] px-5 py-16 sm:px-8 sm:py-20">
          <span className="inline-flex items-center gap-2 rounded-full border border-[#CFE9DE] bg-[#F0FAF6] px-3 py-1.5 text-[11px] font-bold uppercase tracking-[0.12em] text-[#087852]">
            <ShieldCheck size={14} /> Trust Center
          </span>
          <h1 className="font-display mt-6 max-w-[820px] text-[44px] font-semibold leading-[1.02] tracking-[-0.045em] sm:text-[62px]">
            Security claims should be provable.
          </h1>
          <p className="mt-5 max-w-[780px] text-[16px] leading-[1.75] text-[#606780]">
            Linaw separates controls implemented in the product from evidence that requires an independent auditor,
            government agency, bank, or production pilot. We do not convert “the code exists” into a certification claim.
          </p>
        </div>
      </section>

      <section className="mx-auto max-w-[1160px] px-5 py-12 sm:px-8 sm:py-16">
        <div className="grid gap-4 md:grid-cols-3">
          <article className="rounded-[22px] border border-[#E2E5EE] bg-white p-6">
            <LockKeyhole className="text-[#087852]" />
            <p className="mt-5 text-[10px] font-bold uppercase tracking-[0.12em] text-[#9298AA]">Product controls</p>
            <h2 className="mt-2 text-[26px] font-semibold">Built and testable</h2>
            <p className="mt-2 text-[13px] leading-relaxed text-[#687087]">Authentication, authorization, encryption, audit and payroll-control paths are enforced by application code.</p>
          </article>
          <article className="rounded-[22px] border border-[#E2E5EE] bg-white p-6">
            <FileCheck2 className="text-[#4A4AE0]" />
            <p className="mt-5 text-[10px] font-bold uppercase tracking-[0.12em] text-[#9298AA]">Operational evidence</p>
            <h2 className="mt-2 text-[26px] font-semibold">Recorded separately</h2>
            <p className="mt-2 text-[13px] leading-relaxed text-[#687087]">Payroll pilots, filing acceptance, payout UAT and delivery evidence must come from the real external workflow.</p>
          </article>
          <article className="rounded-[22px] border border-[#E2E5EE] bg-white p-6">
            <Network className="text-[#A26610]" />
            <p className="mt-5 text-[10px] font-bold uppercase tracking-[0.12em] text-[#9298AA]">Enterprise identity</p>
            <h2 className="mt-2 text-[26px] font-semibold">OIDC foundation</h2>
            <p className="mt-2 text-[13px] leading-relaxed text-[#687087]">Authorization Code + PKCE is supported when an owner connects a compatible identity provider. SAML and SCIM are not claimed.</p>
          </article>
        </div>

        <div className="mt-12 grid gap-8 lg:grid-cols-[1.1fr_.9fr]">
          <section className="rounded-[24px] border border-[#E2E5EE] bg-white p-6 sm:p-8">
            <div className="flex items-center gap-3">
              <BadgeCheck className="text-[#087852]" />
              <div><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-[#9298AA]">Implemented</p><h2 className="text-[24px] font-semibold">Controls in the product</h2></div>
            </div>
            <div className="mt-6 divide-y divide-[#ECEEF4]">
              {implemented.map(([title, detail]) => (
                <div className="py-4" key={title}>
                  <strong className="text-[14px]">{title}</strong>
                  <p className="mt-1 text-[12.5px] leading-relaxed text-[#6C7388]">{detail}</p>
                </div>
              ))}
            </div>
          </section>

          <section className="rounded-[24px] border border-[#E2E5EE] bg-white p-6 sm:p-8">
            <div className="flex items-center gap-3">
              <CircleAlert className="text-[#A26610]" />
              <div><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-[#9298AA]">External assurance</p><h2 className="text-[24px] font-semibold">Not self-certified</h2></div>
            </div>
            <div className="mt-6 space-y-4">
              {external.map(([title, status, detail]) => (
                <article className="rounded-[15px] border border-[#E8EAF2] bg-[#FAFBFD] p-4" key={title}>
                  <div className="flex items-start justify-between gap-3">
                    <strong className="text-[13px]">{title}</strong>
                    <span className="shrink-0 rounded-full bg-[#FFF4E6] px-2.5 py-1 text-[9.5px] font-bold text-[#8A5300]">{status}</span>
                  </div>
                  <p className="mt-2 text-[11.5px] leading-relaxed text-[#70778C]">{detail}</p>
                </article>
              ))}
            </div>
          </section>
        </div>

        <section className="mt-8 rounded-[24px] border border-[#DADDF0] bg-[#11141F] p-7 text-white sm:p-9">
          <div className="grid gap-6 md:grid-cols-[1fr_auto] md:items-center">
            <div>
              <div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.13em] text-[#AEB4CB]"><KeyRound size={14} /> Procurement boundary</div>
              <h2 className="mt-3 text-[26px] font-semibold">A green CI run is not an ISO certificate, SOC report, government acknowledgement, or bank confirmation.</h2>
              <p className="mt-3 max-w-[780px] text-[13px] leading-relaxed text-[#C5CAD9]">
                Linaw's readiness model keeps those proofs separate so a customer can distinguish implementation, production evidence, and independent attestation.
              </p>
            </div>
          </div>
        </section>
      </section>
      <SiteFooter />
    </main>
  );
}
