"use client";
import { useState } from "react";
import { monthlyTaxEstimate } from "@/lib/monthly-tax-estimate";
const money=(n:number)=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"}).format(n);
export function MonthlyTaxCalculator(){
 const [input,setInput]=useState("30000");
 const value=Number(input);const valid=input.trim()!==""&&Number.isFinite(value)&&value>=0&&value<=1_000_000_000;
 const result=valid?monthlyTaxEstimate(value):null;
 return <section className="mtc" aria-label="Monthly withholding tax calculator"><div className="mtc-input"><p className="mtc-eyebrow">MONTHLY TAXABLE COMPENSATION</p><h2>Start with your taxable pay.</h2><p>Enter taxable compensation after non-taxable items and employee statutory deductions. This is not your gross salary.</p><label htmlFor="monthly-taxable">Monthly taxable compensation (₱)</label><input id="monthly-taxable" inputMode="decimal" type="number" min="0" max="1000000000" step="0.01" value={input} aria-invalid={!valid} aria-describedby="mtc-help mtc-error" onChange={e=>setInput(e.target.value)}/><small id="mtc-help">Monthly table only. Enter an amount from ₱0 to ₱1 billion.</small><p id="mtc-error" role="alert">{valid?"":"Enter a valid monthly taxable compensation amount."}</p><div className="mtc-examples" role="group" aria-label="Sample taxable amounts">{[20000,30000,50000,100000].map(n=><button type="button" key={n} onClick={()=>setInput(String(n))}>{money(n)}</button>)}</div></div><div className="mtc-result"><p className="mtc-eyebrow">ESTIMATED MONTHLY WITHHOLDING TAX</p><output aria-live="polite" aria-atomic="true">{result?money(result.tax):"—"}</output><p>Tax on the taxable compensation entered.</p><dl>{[{label:"Taxable compensation",value:valid?money(value):"—"},{label:"Bracket threshold",value:result?result.rate===0?"Below tax threshold":money(result.floor):"—"},{label:"Base tax",value:result?money(result.base):"—"},{label:"Amount above threshold",value:result?money(result.excess):"—"},{label:"Marginal rate",value:result?`${result.rate*100}%`:"—"},{label:"Tax on excess",value:result?money(result.additional):"—"}].map(row=><div key={row.label}><dt>{row.label}</dt><dd>{row.value}</dd></div>)}</dl><div className="mtc-formula">{result?result.rate?`${money(result.base)} + (${money(result.excess)} × ${result.rate*100}%) = ${money(result.tax)}`:"Monthly taxable compensation of ₱20,833 or below has zero withholding under this table.":"Enter a valid amount to see the calculation."}</div></div></section>;
}
