import Image from "next/image";

const stories = [
  { label: "01 / PEOPLE & HRIS", title: "Start with the people behind the numbers.", copy: "Maintain employee information and organization access. Keep the record connected to payroll, time, and personal self-service.", image: "people", height: 1375, href: "/hris", link: "Explore employee records", tone: "blue" },
  { label: "02 / TIME & ATTENDANCE", title: "Give time records the context they need.", copy: "Review attendance and exceptions alongside workforce workflows. Preserve the schedules and decisions that feed payroll.", image: "attendance", height: 2114, href: "/time-and-attendance", link: "Explore time & attendance", tone: "mint" },
  { label: "03 / PAYROLL REVIEW", title: "Review what changed before money moves.", copy: "Calculate the run, inspect exceptions, and keep payroll preparation, checking, and release responsibilities distinct.", image: "checker", height: 1348, href: "/demo", link: "Explore payroll review", tone: "blue" },
  { label: "04 / REPORTS", title: "Understand the numbers. Prepare the handoff.", copy: "Review payroll history and supported reports. Prepare accounting files and clearly labelled government drafts.", image: "reports", height: 1286, href: "/workforce-analytics", link: "Explore workforce analytics", tone: "mint" },
] as const;

export function ProductHomeStories() {
  return <section id="product" className="lp-product-stories">
    <div className="lp-story-intro"><p className="lp-eyebrow">The workspace</p><h2>One place for the work around payday.<br /><span>From the employee record to the release decision.</span></h2></div>
    {stories.map((story) => <article className="lp-story" key={story.label}><div><p className="lp-eyebrow">{story.label}</p><h3>{story.title}</h3><p className="lp-story-copy">{story.copy}</p><a href={story.href}>{story.link} ↗</a></div><div className={`lp-story-image ${story.tone}`}><a href={`/marketing/screens/${story.image}.webp`} target="_blank" rel="noopener" aria-label={`Open sample ${story.link.toLowerCase()} screen`}><Image src={`/marketing/screens/${story.image}.webp`} alt={`Actual Linaw ${story.link.toLowerCase()} screen with fictional sample data`} width={1440} height={story.height} sizes="(max-width: 760px) 94vw, (max-width: 1240px) 94vw, 1144px" unoptimized /></a></div></article>)}
    <div className="lp-service-grid"><article><p className="lp-eyebrow">People workflows</p><h3>Beyond the employee directory.</h3><p>Recruitment, onboarding, benefits, goals, and performance workflows support the employment lifecycle.</p><a href="/hris">Explore people workflows ↗</a></article><article className="lp-boundaries" id="security"><p className="lp-eyebrow">Access & responsibility</p><h3>The right view for the right role.</h3><p>Company membership, permissions, personal employee access, and audit records support clear operating boundaries.</p><a href="/security">Review security details ↗</a></article></div>
    <div className="lp-service-grid"><article><p className="lp-eyebrow">Managed payroll</p><h3>Need help running the cycle?</h3><p>Discuss payroll processing, exception handoffs, approval responsibilities, and supported outputs.</p><a href="/payroll-outsourcing">Payroll Outsourcing Philippines ↗</a></article><article><p className="lp-eyebrow">Evaluate your fit</p><h3>Start with your operating model.</h3><p>Explore plans for a single team, growing branches, or more complex operations. Review current rates and inclusions.</p><a href="/implementation">Explore implementation ↗</a></article></div>
  </section>;
}
